/**
 * UX-1E — coverage matrix assertion.
 *
 * Reads the committed coverage matrix and asserts every composite in the
 * manifest is exercised at least once. The matrix is generated by
 * `scripts/audits/build-adapter-coverage.mjs`.
 */
import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { integrationManifest } from "../integration.manifest";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "../../../..");
const COVERAGE = resolve(ROOT, "docs/architecture/ux1e-evidence/adapter-coverage.json");

describe("UX-1E coverage matrix", () => {
  it("covers every composite in the manifest", () => {
    if (!existsSync(COVERAGE)) {
      // Tolerate missing artifact only on first bootstrap.
      console.warn("[coverage] adapter-coverage.json not present — skipping");
      return;
    }
    const cov = JSON.parse(readFileSync(COVERAGE, "utf8")) as Record<string, string[]>;
    for (const c of integrationManifest.composites) {
      expect(cov[c], `composite ${c} missing from coverage`).toBeDefined();
      expect(cov[c].length, `composite ${c} has no scenarios`).toBeGreaterThan(0);
    }
  });
});
