/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char91indexChar93RouteImport } from './routes/[index]'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Char91__integration__Char93Ux1eRouteImport } from './routes/[__integration__]/ux1e'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppApprovalsRouteImport } from './routes/_app/approvals'
import { Route as AppAttachmentsRouteImport } from './routes/_app/attachments'
import { Route as AppAttendanceRouteImport } from './routes/_app/attendance'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'
import { Route as AppCollectionsRouteImport } from './routes/_app/collections'
import { Route as AppExpenseCategoriesRouteImport } from './routes/_app/expense-categories'
import { Route as AppExpensesRouteImport } from './routes/_app/expenses'
import { Route as AppInstallRouteImport } from './routes/_app/install'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppKpisRouteImport } from './routes/_app/kpis'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppOpenFileRouteImport } from './routes/_app/open-file'
import { Route as AppPaymentsRouteImport } from './routes/_app/payments'
import { Route as AppPriceListsRouteImport } from './routes/_app/price-lists'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppProtocolRouteImport } from './routes/_app/protocol'
import { Route as AppSalesPipelineRouteImport } from './routes/_app/sales-pipeline'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppShareTargetRouteImport } from './routes/_app/share-target'
import { Route as AppSupplierPaymentsRouteImport } from './routes/_app/supplier-payments'
import { Route as AppSyncRouteImport } from './routes/_app/sync'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as DevPdfJobsRouteImport } from './routes/dev/pdf-jobs'
import { Route as DevPdfSandboxRouteImport } from './routes/dev/pdf-sandbox'
import { Route as DevPdfTelemetryRouteImport } from './routes/dev/pdf-telemetry'
import { Route as PlatformIndexRouteImport } from './routes/platform/index'
import { Route as PlatformAdminsRouteImport } from './routes/platform/admins'
import { Route as PlatformBillingRouteImport } from './routes/platform/billing'
import { Route as PlatformReportsRouteImport } from './routes/platform/reports'
import { Route as PlatformSettingsRouteImport } from './routes/platform/settings'
import { Route as PlatformAuthRouteImport } from './routes/platform_.auth'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable/oauth/consent'
import { Route as AppAccountingIndexRouteImport } from './routes/_app/accounting/index'
import { Route as AppAccountingChartOfAccountsRouteImport } from './routes/_app/accounting/chart-of-accounts'
import { Route as AppAccountingJournalsRouteImport } from './routes/_app/accounting/journals'
import { Route as AppAccountingPostingLogRouteImport } from './routes/_app/accounting/posting-log'
import { Route as AppAdminActivityLogRouteImport } from './routes/_app/admin/activity-log'
import { Route as AppAdminApprovalChainsRouteImport } from './routes/_app/admin/approval-chains'
import { Route as AppAdminAuditTrailRouteImport } from './routes/_app/admin/audit-trail'
import { Route as AppAdminBackupRouteImport } from './routes/_app/admin/backup'
import { Route as AppAdminCustomizationsRouteImport } from './routes/_app/admin/customizations'
import { Route as AppAdminDashboardRouteImport } from './routes/_app/admin/dashboard'
import { Route as AppAdminDomainEventsRouteImport } from './routes/_app/admin/domain-events'
import { Route as AppAdminExportTemplatesRouteImport } from './routes/_app/admin/export-templates'
import { Route as AppAdminMetricsRouteImport } from './routes/_app/admin/metrics'
import { Route as AppAdminPermissionsRouteImport } from './routes/_app/admin/permissions'
import { Route as AppAdminRoleLimitsRouteImport } from './routes/_app/admin/role-limits'
import { Route as AppAdminRolesRouteImport } from './routes/_app/admin/roles'
import { Route as AppAdminSodRulesRouteImport } from './routes/_app/admin/sod-rules'
import { Route as AppAdminTenantsRouteImport } from './routes/_app/admin/tenants'
import { Route as AppAdminUserManagementRouteImport } from './routes/_app/admin/user-management'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppCreditNotesIndexRouteImport } from './routes/_app/credit-notes/index'
import { Route as AppCreditNotesIdRouteImport } from './routes/_app/credit-notes/$id'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers/index'
import { Route as AppCustomersIdRouteImport } from './routes/_app/customers/$id'
import { Route as AppDeliveryNotesIndexRouteImport } from './routes/_app/delivery-notes/index'
import { Route as AppDeliveryNotesIdRouteImport } from './routes/_app/delivery-notes/$id'
import { Route as AppEmployeesIndexRouteImport } from './routes/_app/employees/index'
import { Route as AppEmployeesIdRouteImport } from './routes/_app/employees/$id'
import { Route as AppGoodsReceiptsIndexRouteImport } from './routes/_app/goods-receipts/index'
import { Route as AppGoodsReceiptsIdRouteImport } from './routes/_app/goods-receipts/$id'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app/invoices/index'
import { Route as AppInvoicesIdRouteImport } from './routes/_app/invoices/$id'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products/index'
import { Route as AppProductsIdRouteImport } from './routes/_app/products/$id'
import { Route as AppPurchaseInvoicesIndexRouteImport } from './routes/_app/purchase-invoices/index'
import { Route as AppPurchaseInvoicesIdRouteImport } from './routes/_app/purchase-invoices/$id'
import { Route as AppPurchaseInvoicesApprovalsRouteImport } from './routes/_app/purchase-invoices/approvals'
import { Route as AppPurchaseOrdersIndexRouteImport } from './routes/_app/purchase-orders/index'
import { Route as AppPurchaseOrdersIdRouteImport } from './routes/_app/purchase-orders/$id'
import { Route as AppQuotationsIndexRouteImport } from './routes/_app/quotations/index'
import { Route as AppQuotationsIdRouteImport } from './routes/_app/quotations/$id'
import { Route as AppQuotesIndexRouteImport } from './routes/_app/quotes/index'
import { Route as AppQuotesNewRouteImport } from './routes/_app/quotes/new'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as AppReportsReturnsRouteImport } from './routes/_app/reports/returns'
import { Route as AppReportsSalesRouteImport } from './routes/_app/reports/sales'
import { Route as AppSalesOrdersIndexRouteImport } from './routes/_app/sales-orders/index'
import { Route as AppSalesOrdersIdRouteImport } from './routes/_app/sales-orders/$id'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsAlertsRouteImport } from './routes/_app/settings/alerts'
import { Route as AppSuppliersIndexRouteImport } from './routes/_app/suppliers/index'
import { Route as AppSuppliersIdRouteImport } from './routes/_app/suppliers/$id'
import { Route as AppTreasuryIndexRouteImport } from './routes/_app/treasury/index'
import { Route as AppTreasuryIdRouteImport } from './routes/_app/treasury/$id'
import { Route as PlatformTenantsIndexRouteImport } from './routes/platform/tenants/index'
import { Route as PlatformTenantsIdRouteImport } from './routes/platform/tenants/$id'
import { Route as AppAdminDispatcherBatchesIndexRouteImport } from './routes/_app/admin/dispatcher-batches/index'
import { Route as AppAdminDispatcherBatchesCorrelationIdRouteImport } from './routes/_app/admin/dispatcher-batches/$correlationId'

const Char91indexChar93Route = Char91indexChar93RouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91__integration__Char93Ux1eRoute =
  Char91__integration__Char93Ux1eRouteImport.update({
    id: '/__integration__/ux1e',
    path: '/__integration__/ux1e',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAttachmentsRoute = AppAttachmentsRouteImport.update({
  id: '/attachments',
  path: '/attachments',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsRoute = AppCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AppRoute,
} as any)
const AppExpenseCategoriesRoute = AppExpenseCategoriesRouteImport.update({
  id: '/expense-categories',
  path: '/expense-categories',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppInstallRoute = AppInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppKpisRoute = AppKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppOpenFileRoute = AppOpenFileRouteImport.update({
  id: '/open-file',
  path: '/open-file',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppPriceListsRoute = AppPriceListsRouteImport.update({
  id: '/price-lists',
  path: '/price-lists',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProtocolRoute = AppProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesPipelineRoute = AppSalesPipelineRouteImport.update({
  id: '/sales-pipeline',
  path: '/sales-pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppShareTargetRoute = AppShareTargetRouteImport.update({
  id: '/share-target',
  path: '/share-target',
  getParentRoute: () => AppRoute,
} as any)
const AppSupplierPaymentsRoute = AppSupplierPaymentsRouteImport.update({
  id: '/supplier-payments',
  path: '/supplier-payments',
  getParentRoute: () => AppRoute,
} as any)
const AppSyncRoute = AppSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const DevPdfJobsRoute = DevPdfJobsRouteImport.update({
  id: '/dev/pdf-jobs',
  path: '/dev/pdf-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DevPdfSandboxRoute = DevPdfSandboxRouteImport.update({
  id: '/dev/pdf-sandbox',
  path: '/dev/pdf-sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DevPdfTelemetryRoute = DevPdfTelemetryRouteImport.update({
  id: '/dev/pdf-telemetry',
  path: '/dev/pdf-telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformAdminsRoute = PlatformAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformBillingRoute = PlatformBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformReportsRoute = PlatformReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformSettingsRoute = PlatformSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformAuthRoute = PlatformAuthRouteImport.update({
  id: '/platform_/auth',
  path: '/platform/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountingIndexRoute = AppAccountingIndexRouteImport.update({
  id: '/accounting/',
  path: '/accounting/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingChartOfAccountsRoute =
  AppAccountingChartOfAccountsRouteImport.update({
    id: '/accounting/chart-of-accounts',
    path: '/accounting/chart-of-accounts',
    getParentRoute: () => AppRoute,
  } as any)
const AppAccountingJournalsRoute = AppAccountingJournalsRouteImport.update({
  id: '/accounting/journals',
  path: '/accounting/journals',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingPostingLogRoute = AppAccountingPostingLogRouteImport.update({
  id: '/accounting/posting-log',
  path: '/accounting/posting-log',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminActivityLogRoute = AppAdminActivityLogRouteImport.update({
  id: '/activity-log',
  path: '/activity-log',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminApprovalChainsRoute = AppAdminApprovalChainsRouteImport.update({
  id: '/approval-chains',
  path: '/approval-chains',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditTrailRoute = AppAdminAuditTrailRouteImport.update({
  id: '/audit-trail',
  path: '/audit-trail',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBackupRoute = AppAdminBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminCustomizationsRoute = AppAdminCustomizationsRouteImport.update({
  id: '/customizations',
  path: '/customizations',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDomainEventsRoute = AppAdminDomainEventsRouteImport.update({
  id: '/domain-events',
  path: '/domain-events',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminExportTemplatesRoute = AppAdminExportTemplatesRouteImport.update({
  id: '/export-templates',
  path: '/export-templates',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMetricsRoute = AppAdminMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPermissionsRoute = AppAdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRoleLimitsRoute = AppAdminRoleLimitsRouteImport.update({
  id: '/role-limits',
  path: '/role-limits',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRolesRoute = AppAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSodRulesRoute = AppAdminSodRulesRouteImport.update({
  id: '/sod-rules',
  path: '/sod-rules',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminTenantsRoute = AppAdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUserManagementRoute = AppAdminUserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppCreditNotesIndexRoute = AppCreditNotesIndexRouteImport.update({
  id: '/credit-notes/',
  path: '/credit-notes/',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditNotesIdRoute = AppCreditNotesIdRouteImport.update({
  id: '/credit-notes/$id',
  path: '/credit-notes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveryNotesIndexRoute = AppDeliveryNotesIndexRouteImport.update({
  id: '/delivery-notes/',
  path: '/delivery-notes/',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveryNotesIdRoute = AppDeliveryNotesIdRouteImport.update({
  id: '/delivery-notes/$id',
  path: '/delivery-notes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIndexRoute = AppEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIdRoute = AppEmployeesIdRouteImport.update({
  id: '/employees/$id',
  path: '/employees/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppGoodsReceiptsIndexRoute = AppGoodsReceiptsIndexRouteImport.update({
  id: '/goods-receipts/',
  path: '/goods-receipts/',
  getParentRoute: () => AppRoute,
} as any)
const AppGoodsReceiptsIdRoute = AppGoodsReceiptsIdRouteImport.update({
  id: '/goods-receipts/$id',
  path: '/goods-receipts/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIdRoute = AppInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIdRoute = AppProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseInvoicesIndexRoute =
  AppPurchaseInvoicesIndexRouteImport.update({
    id: '/purchase-invoices/',
    path: '/purchase-invoices/',
    getParentRoute: () => AppRoute,
  } as any)
const AppPurchaseInvoicesIdRoute = AppPurchaseInvoicesIdRouteImport.update({
  id: '/purchase-invoices/$id',
  path: '/purchase-invoices/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseInvoicesApprovalsRoute =
  AppPurchaseInvoicesApprovalsRouteImport.update({
    id: '/purchase-invoices/approvals',
    path: '/purchase-invoices/approvals',
    getParentRoute: () => AppRoute,
  } as any)
const AppPurchaseOrdersIndexRoute = AppPurchaseOrdersIndexRouteImport.update({
  id: '/purchase-orders/',
  path: '/purchase-orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersIdRoute = AppPurchaseOrdersIdRouteImport.update({
  id: '/purchase-orders/$id',
  path: '/purchase-orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsIndexRoute = AppQuotationsIndexRouteImport.update({
  id: '/quotations/',
  path: '/quotations/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsIdRoute = AppQuotationsIdRouteImport.update({
  id: '/quotations/$id',
  path: '/quotations/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesIndexRoute = AppQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesNewRoute = AppQuotesNewRouteImport.update({
  id: '/quotes/new',
  path: '/quotes/new',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsReturnsRoute = AppReportsReturnsRouteImport.update({
  id: '/reports/returns',
  path: '/reports/returns',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsSalesRoute = AppReportsSalesRouteImport.update({
  id: '/reports/sales',
  path: '/reports/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesOrdersIndexRoute = AppSalesOrdersIndexRouteImport.update({
  id: '/sales-orders/',
  path: '/sales-orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesOrdersIdRoute = AppSalesOrdersIdRouteImport.update({
  id: '/sales-orders/$id',
  path: '/sales-orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAlertsRoute = AppSettingsAlertsRouteImport.update({
  id: '/settings/alerts',
  path: '/settings/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersIndexRoute = AppSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersIdRoute = AppSuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTreasuryIndexRoute = AppTreasuryIndexRouteImport.update({
  id: '/treasury/',
  path: '/treasury/',
  getParentRoute: () => AppRoute,
} as any)
const AppTreasuryIdRoute = AppTreasuryIdRouteImport.update({
  id: '/treasury/$id',
  path: '/treasury/$id',
  getParentRoute: () => AppRoute,
} as any)
const PlatformTenantsIndexRoute = PlatformTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformTenantsIdRoute = PlatformTenantsIdRouteImport.update({
  id: '/tenants/$id',
  path: '/tenants/$id',
  getParentRoute: () => PlatformRoute,
} as any)
const AppAdminDispatcherBatchesIndexRoute =
  AppAdminDispatcherBatchesIndexRouteImport.update({
    id: '/dispatcher-batches/',
    path: '/dispatcher-batches/',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminDispatcherBatchesCorrelationIdRoute =
  AppAdminDispatcherBatchesCorrelationIdRouteImport.update({
    id: '/dispatcher-batches/$correlationId',
    path: '/dispatcher-batches/$correlationId',
    getParentRoute: () => AppAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/index': typeof Char91indexChar93Route
  '/landing': typeof LandingRoute
  '/platform': typeof PlatformRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/__integration__/ux1e': typeof Char91__integration__Char93Ux1eRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/approvals': typeof AppApprovalsRoute
  '/attachments': typeof AppAttachmentsRoute
  '/attendance': typeof AppAttendanceRoute
  '/categories': typeof AppCategoriesRoute
  '/collections': typeof AppCollectionsRoute
  '/expense-categories': typeof AppExpenseCategoriesRoute
  '/expenses': typeof AppExpensesRoute
  '/install': typeof AppInstallRoute
  '/inventory': typeof AppInventoryRoute
  '/kpis': typeof AppKpisRoute
  '/notifications': typeof AppNotificationsRoute
  '/open-file': typeof AppOpenFileRoute
  '/payments': typeof AppPaymentsRoute
  '/price-lists': typeof AppPriceListsRoute
  '/profile': typeof AppProfileRoute
  '/protocol': typeof AppProtocolRoute
  '/sales-pipeline': typeof AppSalesPipelineRoute
  '/search': typeof AppSearchRoute
  '/share-target': typeof AppShareTargetRoute
  '/supplier-payments': typeof AppSupplierPaymentsRoute
  '/sync': typeof AppSyncRoute
  '/tasks': typeof AppTasksRoute
  '/dev/pdf-jobs': typeof DevPdfJobsRoute
  '/dev/pdf-sandbox': typeof DevPdfSandboxRoute
  '/dev/pdf-telemetry': typeof DevPdfTelemetryRoute
  '/platform/admins': typeof PlatformAdminsRoute
  '/platform/billing': typeof PlatformBillingRoute
  '/platform/reports': typeof PlatformReportsRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/platform/auth': typeof PlatformAuthRoute
  '/platform/': typeof PlatformIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/accounting/chart-of-accounts': typeof AppAccountingChartOfAccountsRoute
  '/accounting/journals': typeof AppAccountingJournalsRoute
  '/accounting/posting-log': typeof AppAccountingPostingLogRoute
  '/admin/activity-log': typeof AppAdminActivityLogRoute
  '/admin/approval-chains': typeof AppAdminApprovalChainsRoute
  '/admin/audit-trail': typeof AppAdminAuditTrailRoute
  '/admin/backup': typeof AppAdminBackupRoute
  '/admin/customizations': typeof AppAdminCustomizationsRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/domain-events': typeof AppAdminDomainEventsRoute
  '/admin/export-templates': typeof AppAdminExportTemplatesRoute
  '/admin/metrics': typeof AppAdminMetricsRoute
  '/admin/permissions': typeof AppAdminPermissionsRoute
  '/admin/role-limits': typeof AppAdminRoleLimitsRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/sod-rules': typeof AppAdminSodRulesRoute
  '/admin/tenants': typeof AppAdminTenantsRoute
  '/admin/user-management': typeof AppAdminUserManagementRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/credit-notes/$id': typeof AppCreditNotesIdRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/delivery-notes/$id': typeof AppDeliveryNotesIdRoute
  '/employees/$id': typeof AppEmployeesIdRoute
  '/goods-receipts/$id': typeof AppGoodsReceiptsIdRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/products/$id': typeof AppProductsIdRoute
  '/purchase-invoices/$id': typeof AppPurchaseInvoicesIdRoute
  '/purchase-invoices/approvals': typeof AppPurchaseInvoicesApprovalsRoute
  '/purchase-orders/$id': typeof AppPurchaseOrdersIdRoute
  '/quotations/$id': typeof AppQuotationsIdRoute
  '/quotes/new': typeof AppQuotesNewRoute
  '/reports/returns': typeof AppReportsReturnsRoute
  '/reports/sales': typeof AppReportsSalesRoute
  '/sales-orders/$id': typeof AppSalesOrdersIdRoute
  '/settings/alerts': typeof AppSettingsAlertsRoute
  '/suppliers/$id': typeof AppSuppliersIdRoute
  '/treasury/$id': typeof AppTreasuryIdRoute
  '/platform/tenants/$id': typeof PlatformTenantsIdRoute
  '/accounting/': typeof AppAccountingIndexRoute
  '/credit-notes/': typeof AppCreditNotesIndexRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/delivery-notes/': typeof AppDeliveryNotesIndexRoute
  '/employees/': typeof AppEmployeesIndexRoute
  '/goods-receipts/': typeof AppGoodsReceiptsIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/purchase-invoices/': typeof AppPurchaseInvoicesIndexRoute
  '/purchase-orders/': typeof AppPurchaseOrdersIndexRoute
  '/quotations/': typeof AppQuotationsIndexRoute
  '/quotes/': typeof AppQuotesIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/sales-orders/': typeof AppSalesOrdersIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/suppliers/': typeof AppSuppliersIndexRoute
  '/treasury/': typeof AppTreasuryIndexRoute
  '/platform/tenants/': typeof PlatformTenantsIndexRoute
  '/admin/dispatcher-batches/$correlationId': typeof AppAdminDispatcherBatchesCorrelationIdRoute
  '/admin/dispatcher-batches/': typeof AppAdminDispatcherBatchesIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/index': typeof Char91indexChar93Route
  '/landing': typeof LandingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/__integration__/ux1e': typeof Char91__integration__Char93Ux1eRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/approvals': typeof AppApprovalsRoute
  '/attachments': typeof AppAttachmentsRoute
  '/attendance': typeof AppAttendanceRoute
  '/categories': typeof AppCategoriesRoute
  '/collections': typeof AppCollectionsRoute
  '/expense-categories': typeof AppExpenseCategoriesRoute
  '/expenses': typeof AppExpensesRoute
  '/install': typeof AppInstallRoute
  '/inventory': typeof AppInventoryRoute
  '/kpis': typeof AppKpisRoute
  '/notifications': typeof AppNotificationsRoute
  '/open-file': typeof AppOpenFileRoute
  '/payments': typeof AppPaymentsRoute
  '/price-lists': typeof AppPriceListsRoute
  '/profile': typeof AppProfileRoute
  '/protocol': typeof AppProtocolRoute
  '/sales-pipeline': typeof AppSalesPipelineRoute
  '/search': typeof AppSearchRoute
  '/share-target': typeof AppShareTargetRoute
  '/supplier-payments': typeof AppSupplierPaymentsRoute
  '/sync': typeof AppSyncRoute
  '/tasks': typeof AppTasksRoute
  '/dev/pdf-jobs': typeof DevPdfJobsRoute
  '/dev/pdf-sandbox': typeof DevPdfSandboxRoute
  '/dev/pdf-telemetry': typeof DevPdfTelemetryRoute
  '/platform/admins': typeof PlatformAdminsRoute
  '/platform/billing': typeof PlatformBillingRoute
  '/platform/reports': typeof PlatformReportsRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/platform/auth': typeof PlatformAuthRoute
  '/': typeof AppIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/accounting/chart-of-accounts': typeof AppAccountingChartOfAccountsRoute
  '/accounting/journals': typeof AppAccountingJournalsRoute
  '/accounting/posting-log': typeof AppAccountingPostingLogRoute
  '/admin/activity-log': typeof AppAdminActivityLogRoute
  '/admin/approval-chains': typeof AppAdminApprovalChainsRoute
  '/admin/audit-trail': typeof AppAdminAuditTrailRoute
  '/admin/backup': typeof AppAdminBackupRoute
  '/admin/customizations': typeof AppAdminCustomizationsRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/domain-events': typeof AppAdminDomainEventsRoute
  '/admin/export-templates': typeof AppAdminExportTemplatesRoute
  '/admin/metrics': typeof AppAdminMetricsRoute
  '/admin/permissions': typeof AppAdminPermissionsRoute
  '/admin/role-limits': typeof AppAdminRoleLimitsRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/sod-rules': typeof AppAdminSodRulesRoute
  '/admin/tenants': typeof AppAdminTenantsRoute
  '/admin/user-management': typeof AppAdminUserManagementRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/credit-notes/$id': typeof AppCreditNotesIdRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/delivery-notes/$id': typeof AppDeliveryNotesIdRoute
  '/employees/$id': typeof AppEmployeesIdRoute
  '/goods-receipts/$id': typeof AppGoodsReceiptsIdRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/products/$id': typeof AppProductsIdRoute
  '/purchase-invoices/$id': typeof AppPurchaseInvoicesIdRoute
  '/purchase-invoices/approvals': typeof AppPurchaseInvoicesApprovalsRoute
  '/purchase-orders/$id': typeof AppPurchaseOrdersIdRoute
  '/quotations/$id': typeof AppQuotationsIdRoute
  '/quotes/new': typeof AppQuotesNewRoute
  '/reports/returns': typeof AppReportsReturnsRoute
  '/reports/sales': typeof AppReportsSalesRoute
  '/sales-orders/$id': typeof AppSalesOrdersIdRoute
  '/settings/alerts': typeof AppSettingsAlertsRoute
  '/suppliers/$id': typeof AppSuppliersIdRoute
  '/treasury/$id': typeof AppTreasuryIdRoute
  '/platform/tenants/$id': typeof PlatformTenantsIdRoute
  '/accounting': typeof AppAccountingIndexRoute
  '/credit-notes': typeof AppCreditNotesIndexRoute
  '/customers': typeof AppCustomersIndexRoute
  '/delivery-notes': typeof AppDeliveryNotesIndexRoute
  '/employees': typeof AppEmployeesIndexRoute
  '/goods-receipts': typeof AppGoodsReceiptsIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/purchase-invoices': typeof AppPurchaseInvoicesIndexRoute
  '/purchase-orders': typeof AppPurchaseOrdersIndexRoute
  '/quotations': typeof AppQuotationsIndexRoute
  '/quotes': typeof AppQuotesIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/sales-orders': typeof AppSalesOrdersIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/suppliers': typeof AppSuppliersIndexRoute
  '/treasury': typeof AppTreasuryIndexRoute
  '/platform/tenants': typeof PlatformTenantsIndexRoute
  '/admin/dispatcher-batches/$correlationId': typeof AppAdminDispatcherBatchesCorrelationIdRoute
  '/admin/dispatcher-batches': typeof AppAdminDispatcherBatchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/index': typeof Char91indexChar93Route
  '/landing': typeof LandingRoute
  '/platform': typeof PlatformRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/__integration__/ux1e': typeof Char91__integration__Char93Ux1eRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/attachments': typeof AppAttachmentsRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/collections': typeof AppCollectionsRoute
  '/_app/expense-categories': typeof AppExpenseCategoriesRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/install': typeof AppInstallRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/kpis': typeof AppKpisRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/open-file': typeof AppOpenFileRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/price-lists': typeof AppPriceListsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/protocol': typeof AppProtocolRoute
  '/_app/sales-pipeline': typeof AppSalesPipelineRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/share-target': typeof AppShareTargetRoute
  '/_app/supplier-payments': typeof AppSupplierPaymentsRoute
  '/_app/sync': typeof AppSyncRoute
  '/_app/tasks': typeof AppTasksRoute
  '/dev/pdf-jobs': typeof DevPdfJobsRoute
  '/dev/pdf-sandbox': typeof DevPdfSandboxRoute
  '/dev/pdf-telemetry': typeof DevPdfTelemetryRoute
  '/platform/admins': typeof PlatformAdminsRoute
  '/platform/billing': typeof PlatformBillingRoute
  '/platform/reports': typeof PlatformReportsRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/platform_/auth': typeof PlatformAuthRoute
  '/_app/': typeof AppIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_app/accounting/chart-of-accounts': typeof AppAccountingChartOfAccountsRoute
  '/_app/accounting/journals': typeof AppAccountingJournalsRoute
  '/_app/accounting/posting-log': typeof AppAccountingPostingLogRoute
  '/_app/admin/activity-log': typeof AppAdminActivityLogRoute
  '/_app/admin/approval-chains': typeof AppAdminApprovalChainsRoute
  '/_app/admin/audit-trail': typeof AppAdminAuditTrailRoute
  '/_app/admin/backup': typeof AppAdminBackupRoute
  '/_app/admin/customizations': typeof AppAdminCustomizationsRoute
  '/_app/admin/dashboard': typeof AppAdminDashboardRoute
  '/_app/admin/domain-events': typeof AppAdminDomainEventsRoute
  '/_app/admin/export-templates': typeof AppAdminExportTemplatesRoute
  '/_app/admin/metrics': typeof AppAdminMetricsRoute
  '/_app/admin/permissions': typeof AppAdminPermissionsRoute
  '/_app/admin/role-limits': typeof AppAdminRoleLimitsRoute
  '/_app/admin/roles': typeof AppAdminRolesRoute
  '/_app/admin/sod-rules': typeof AppAdminSodRulesRoute
  '/_app/admin/tenants': typeof AppAdminTenantsRoute
  '/_app/admin/user-management': typeof AppAdminUserManagementRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/credit-notes/$id': typeof AppCreditNotesIdRoute
  '/_app/customers/$id': typeof AppCustomersIdRoute
  '/_app/delivery-notes/$id': typeof AppDeliveryNotesIdRoute
  '/_app/employees/$id': typeof AppEmployeesIdRoute
  '/_app/goods-receipts/$id': typeof AppGoodsReceiptsIdRoute
  '/_app/invoices/$id': typeof AppInvoicesIdRoute
  '/_app/products/$id': typeof AppProductsIdRoute
  '/_app/purchase-invoices/$id': typeof AppPurchaseInvoicesIdRoute
  '/_app/purchase-invoices/approvals': typeof AppPurchaseInvoicesApprovalsRoute
  '/_app/purchase-orders/$id': typeof AppPurchaseOrdersIdRoute
  '/_app/quotations/$id': typeof AppQuotationsIdRoute
  '/_app/quotes/new': typeof AppQuotesNewRoute
  '/_app/reports/returns': typeof AppReportsReturnsRoute
  '/_app/reports/sales': typeof AppReportsSalesRoute
  '/_app/sales-orders/$id': typeof AppSalesOrdersIdRoute
  '/_app/settings/alerts': typeof AppSettingsAlertsRoute
  '/_app/suppliers/$id': typeof AppSuppliersIdRoute
  '/_app/treasury/$id': typeof AppTreasuryIdRoute
  '/platform/tenants/$id': typeof PlatformTenantsIdRoute
  '/_app/accounting/': typeof AppAccountingIndexRoute
  '/_app/credit-notes/': typeof AppCreditNotesIndexRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/delivery-notes/': typeof AppDeliveryNotesIndexRoute
  '/_app/employees/': typeof AppEmployeesIndexRoute
  '/_app/goods-receipts/': typeof AppGoodsReceiptsIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/purchase-invoices/': typeof AppPurchaseInvoicesIndexRoute
  '/_app/purchase-orders/': typeof AppPurchaseOrdersIndexRoute
  '/_app/quotations/': typeof AppQuotationsIndexRoute
  '/_app/quotes/': typeof AppQuotesIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/sales-orders/': typeof AppSalesOrdersIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/suppliers/': typeof AppSuppliersIndexRoute
  '/_app/treasury/': typeof AppTreasuryIndexRoute
  '/platform/tenants/': typeof PlatformTenantsIndexRoute
  '/_app/admin/dispatcher-batches/$correlationId': typeof AppAdminDispatcherBatchesCorrelationIdRoute
  '/_app/admin/dispatcher-batches/': typeof AppAdminDispatcherBatchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/index'
    | '/landing'
    | '/platform'
    | '/reset-password'
    | '/__integration__/ux1e'
    | '/admin'
    | '/approvals'
    | '/attachments'
    | '/attendance'
    | '/categories'
    | '/collections'
    | '/expense-categories'
    | '/expenses'
    | '/install'
    | '/inventory'
    | '/kpis'
    | '/notifications'
    | '/open-file'
    | '/payments'
    | '/price-lists'
    | '/profile'
    | '/protocol'
    | '/sales-pipeline'
    | '/search'
    | '/share-target'
    | '/supplier-payments'
    | '/sync'
    | '/tasks'
    | '/dev/pdf-jobs'
    | '/dev/pdf-sandbox'
    | '/dev/pdf-telemetry'
    | '/platform/admins'
    | '/platform/billing'
    | '/platform/reports'
    | '/platform/settings'
    | '/platform/auth'
    | '/platform/'
    | '/.lovable/oauth/consent'
    | '/accounting/chart-of-accounts'
    | '/accounting/journals'
    | '/accounting/posting-log'
    | '/admin/activity-log'
    | '/admin/approval-chains'
    | '/admin/audit-trail'
    | '/admin/backup'
    | '/admin/customizations'
    | '/admin/dashboard'
    | '/admin/domain-events'
    | '/admin/export-templates'
    | '/admin/metrics'
    | '/admin/permissions'
    | '/admin/role-limits'
    | '/admin/roles'
    | '/admin/sod-rules'
    | '/admin/tenants'
    | '/admin/user-management'
    | '/admin/users'
    | '/credit-notes/$id'
    | '/customers/$id'
    | '/delivery-notes/$id'
    | '/employees/$id'
    | '/goods-receipts/$id'
    | '/invoices/$id'
    | '/products/$id'
    | '/purchase-invoices/$id'
    | '/purchase-invoices/approvals'
    | '/purchase-orders/$id'
    | '/quotations/$id'
    | '/quotes/new'
    | '/reports/returns'
    | '/reports/sales'
    | '/sales-orders/$id'
    | '/settings/alerts'
    | '/suppliers/$id'
    | '/treasury/$id'
    | '/platform/tenants/$id'
    | '/accounting/'
    | '/credit-notes/'
    | '/customers/'
    | '/delivery-notes/'
    | '/employees/'
    | '/goods-receipts/'
    | '/invoices/'
    | '/products/'
    | '/purchase-invoices/'
    | '/purchase-orders/'
    | '/quotations/'
    | '/quotes/'
    | '/reports/'
    | '/sales-orders/'
    | '/settings/'
    | '/suppliers/'
    | '/treasury/'
    | '/platform/tenants/'
    | '/admin/dispatcher-batches/$correlationId'
    | '/admin/dispatcher-batches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/forgot-password'
    | '/index'
    | '/landing'
    | '/reset-password'
    | '/__integration__/ux1e'
    | '/admin'
    | '/approvals'
    | '/attachments'
    | '/attendance'
    | '/categories'
    | '/collections'
    | '/expense-categories'
    | '/expenses'
    | '/install'
    | '/inventory'
    | '/kpis'
    | '/notifications'
    | '/open-file'
    | '/payments'
    | '/price-lists'
    | '/profile'
    | '/protocol'
    | '/sales-pipeline'
    | '/search'
    | '/share-target'
    | '/supplier-payments'
    | '/sync'
    | '/tasks'
    | '/dev/pdf-jobs'
    | '/dev/pdf-sandbox'
    | '/dev/pdf-telemetry'
    | '/platform/admins'
    | '/platform/billing'
    | '/platform/reports'
    | '/platform/settings'
    | '/platform/auth'
    | '/'
    | '/platform'
    | '/.lovable/oauth/consent'
    | '/accounting/chart-of-accounts'
    | '/accounting/journals'
    | '/accounting/posting-log'
    | '/admin/activity-log'
    | '/admin/approval-chains'
    | '/admin/audit-trail'
    | '/admin/backup'
    | '/admin/customizations'
    | '/admin/dashboard'
    | '/admin/domain-events'
    | '/admin/export-templates'
    | '/admin/metrics'
    | '/admin/permissions'
    | '/admin/role-limits'
    | '/admin/roles'
    | '/admin/sod-rules'
    | '/admin/tenants'
    | '/admin/user-management'
    | '/admin/users'
    | '/credit-notes/$id'
    | '/customers/$id'
    | '/delivery-notes/$id'
    | '/employees/$id'
    | '/goods-receipts/$id'
    | '/invoices/$id'
    | '/products/$id'
    | '/purchase-invoices/$id'
    | '/purchase-invoices/approvals'
    | '/purchase-orders/$id'
    | '/quotations/$id'
    | '/quotes/new'
    | '/reports/returns'
    | '/reports/sales'
    | '/sales-orders/$id'
    | '/settings/alerts'
    | '/suppliers/$id'
    | '/treasury/$id'
    | '/platform/tenants/$id'
    | '/accounting'
    | '/credit-notes'
    | '/customers'
    | '/delivery-notes'
    | '/employees'
    | '/goods-receipts'
    | '/invoices'
    | '/products'
    | '/purchase-invoices'
    | '/purchase-orders'
    | '/quotations'
    | '/quotes'
    | '/reports'
    | '/sales-orders'
    | '/settings'
    | '/suppliers'
    | '/treasury'
    | '/platform/tenants'
    | '/admin/dispatcher-batches/$correlationId'
    | '/admin/dispatcher-batches'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/forgot-password'
    | '/index'
    | '/landing'
    | '/platform'
    | '/reset-password'
    | '/__integration__/ux1e'
    | '/_app/admin'
    | '/_app/approvals'
    | '/_app/attachments'
    | '/_app/attendance'
    | '/_app/categories'
    | '/_app/collections'
    | '/_app/expense-categories'
    | '/_app/expenses'
    | '/_app/install'
    | '/_app/inventory'
    | '/_app/kpis'
    | '/_app/notifications'
    | '/_app/open-file'
    | '/_app/payments'
    | '/_app/price-lists'
    | '/_app/profile'
    | '/_app/protocol'
    | '/_app/sales-pipeline'
    | '/_app/search'
    | '/_app/share-target'
    | '/_app/supplier-payments'
    | '/_app/sync'
    | '/_app/tasks'
    | '/dev/pdf-jobs'
    | '/dev/pdf-sandbox'
    | '/dev/pdf-telemetry'
    | '/platform/admins'
    | '/platform/billing'
    | '/platform/reports'
    | '/platform/settings'
    | '/platform_/auth'
    | '/_app/'
    | '/platform/'
    | '/.lovable/oauth/consent'
    | '/_app/accounting/chart-of-accounts'
    | '/_app/accounting/journals'
    | '/_app/accounting/posting-log'
    | '/_app/admin/activity-log'
    | '/_app/admin/approval-chains'
    | '/_app/admin/audit-trail'
    | '/_app/admin/backup'
    | '/_app/admin/customizations'
    | '/_app/admin/dashboard'
    | '/_app/admin/domain-events'
    | '/_app/admin/export-templates'
    | '/_app/admin/metrics'
    | '/_app/admin/permissions'
    | '/_app/admin/role-limits'
    | '/_app/admin/roles'
    | '/_app/admin/sod-rules'
    | '/_app/admin/tenants'
    | '/_app/admin/user-management'
    | '/_app/admin/users'
    | '/_app/credit-notes/$id'
    | '/_app/customers/$id'
    | '/_app/delivery-notes/$id'
    | '/_app/employees/$id'
    | '/_app/goods-receipts/$id'
    | '/_app/invoices/$id'
    | '/_app/products/$id'
    | '/_app/purchase-invoices/$id'
    | '/_app/purchase-invoices/approvals'
    | '/_app/purchase-orders/$id'
    | '/_app/quotations/$id'
    | '/_app/quotes/new'
    | '/_app/reports/returns'
    | '/_app/reports/sales'
    | '/_app/sales-orders/$id'
    | '/_app/settings/alerts'
    | '/_app/suppliers/$id'
    | '/_app/treasury/$id'
    | '/platform/tenants/$id'
    | '/_app/accounting/'
    | '/_app/credit-notes/'
    | '/_app/customers/'
    | '/_app/delivery-notes/'
    | '/_app/employees/'
    | '/_app/goods-receipts/'
    | '/_app/invoices/'
    | '/_app/products/'
    | '/_app/purchase-invoices/'
    | '/_app/purchase-orders/'
    | '/_app/quotations/'
    | '/_app/quotes/'
    | '/_app/reports/'
    | '/_app/sales-orders/'
    | '/_app/settings/'
    | '/_app/suppliers/'
    | '/_app/treasury/'
    | '/platform/tenants/'
    | '/_app/admin/dispatcher-batches/$correlationId'
    | '/_app/admin/dispatcher-batches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  Char91indexChar93Route: typeof Char91indexChar93Route
  LandingRoute: typeof LandingRoute
  PlatformRoute: typeof PlatformRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91__integration__Char93Ux1eRoute: typeof Char91__integration__Char93Ux1eRoute
  DevPdfJobsRoute: typeof DevPdfJobsRoute
  DevPdfSandboxRoute: typeof DevPdfSandboxRoute
  DevPdfTelemetryRoute: typeof DevPdfTelemetryRoute
  PlatformAuthRoute: typeof PlatformAuthRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index': {
      id: '/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof Char91indexChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__integration__/ux1e': {
      id: '/__integration__/ux1e'
      path: '/__integration__/ux1e'
      fullPath: '/__integration__/ux1e'
      preLoaderRoute: typeof Char91__integration__Char93Ux1eRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attachments': {
      id: '/_app/attachments'
      path: '/attachments'
      fullPath: '/attachments'
      preLoaderRoute: typeof AppAttachmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections': {
      id: '/_app/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AppCollectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expense-categories': {
      id: '/_app/expense-categories'
      path: '/expense-categories'
      fullPath: '/expense-categories'
      preLoaderRoute: typeof AppExpenseCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/install': {
      id: '/_app/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof AppInstallRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kpis': {
      id: '/_app/kpis'
      path: '/kpis'
      fullPath: '/kpis'
      preLoaderRoute: typeof AppKpisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/open-file': {
      id: '/_app/open-file'
      path: '/open-file'
      fullPath: '/open-file'
      preLoaderRoute: typeof AppOpenFileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/price-lists': {
      id: '/_app/price-lists'
      path: '/price-lists'
      fullPath: '/price-lists'
      preLoaderRoute: typeof AppPriceListsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/protocol': {
      id: '/_app/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof AppProtocolRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales-pipeline': {
      id: '/_app/sales-pipeline'
      path: '/sales-pipeline'
      fullPath: '/sales-pipeline'
      preLoaderRoute: typeof AppSalesPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/share-target': {
      id: '/_app/share-target'
      path: '/share-target'
      fullPath: '/share-target'
      preLoaderRoute: typeof AppShareTargetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/supplier-payments': {
      id: '/_app/supplier-payments'
      path: '/supplier-payments'
      fullPath: '/supplier-payments'
      preLoaderRoute: typeof AppSupplierPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sync': {
      id: '/_app/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof AppSyncRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/dev/pdf-jobs': {
      id: '/dev/pdf-jobs'
      path: '/dev/pdf-jobs'
      fullPath: '/dev/pdf-jobs'
      preLoaderRoute: typeof DevPdfJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/pdf-sandbox': {
      id: '/dev/pdf-sandbox'
      path: '/dev/pdf-sandbox'
      fullPath: '/dev/pdf-sandbox'
      preLoaderRoute: typeof DevPdfSandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/pdf-telemetry': {
      id: '/dev/pdf-telemetry'
      path: '/dev/pdf-telemetry'
      fullPath: '/dev/pdf-telemetry'
      preLoaderRoute: typeof DevPdfTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/admins': {
      id: '/platform/admins'
      path: '/admins'
      fullPath: '/platform/admins'
      preLoaderRoute: typeof PlatformAdminsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/billing': {
      id: '/platform/billing'
      path: '/billing'
      fullPath: '/platform/billing'
      preLoaderRoute: typeof PlatformBillingRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/reports': {
      id: '/platform/reports'
      path: '/reports'
      fullPath: '/platform/reports'
      preLoaderRoute: typeof PlatformReportsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/settings': {
      id: '/platform/settings'
      path: '/settings'
      fullPath: '/platform/settings'
      preLoaderRoute: typeof PlatformSettingsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform_/auth': {
      id: '/platform_/auth'
      path: '/platform/auth'
      fullPath: '/platform/auth'
      preLoaderRoute: typeof PlatformAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/accounting/': {
      id: '/_app/accounting/'
      path: '/accounting'
      fullPath: '/accounting/'
      preLoaderRoute: typeof AppAccountingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/chart-of-accounts': {
      id: '/_app/accounting/chart-of-accounts'
      path: '/accounting/chart-of-accounts'
      fullPath: '/accounting/chart-of-accounts'
      preLoaderRoute: typeof AppAccountingChartOfAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/journals': {
      id: '/_app/accounting/journals'
      path: '/accounting/journals'
      fullPath: '/accounting/journals'
      preLoaderRoute: typeof AppAccountingJournalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/posting-log': {
      id: '/_app/accounting/posting-log'
      path: '/accounting/posting-log'
      fullPath: '/accounting/posting-log'
      preLoaderRoute: typeof AppAccountingPostingLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/activity-log': {
      id: '/_app/admin/activity-log'
      path: '/activity-log'
      fullPath: '/admin/activity-log'
      preLoaderRoute: typeof AppAdminActivityLogRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/approval-chains': {
      id: '/_app/admin/approval-chains'
      path: '/approval-chains'
      fullPath: '/admin/approval-chains'
      preLoaderRoute: typeof AppAdminApprovalChainsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/audit-trail': {
      id: '/_app/admin/audit-trail'
      path: '/audit-trail'
      fullPath: '/admin/audit-trail'
      preLoaderRoute: typeof AppAdminAuditTrailRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/backup': {
      id: '/_app/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AppAdminBackupRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/customizations': {
      id: '/_app/admin/customizations'
      path: '/customizations'
      fullPath: '/admin/customizations'
      preLoaderRoute: typeof AppAdminCustomizationsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/dashboard': {
      id: '/_app/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/domain-events': {
      id: '/_app/admin/domain-events'
      path: '/domain-events'
      fullPath: '/admin/domain-events'
      preLoaderRoute: typeof AppAdminDomainEventsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/export-templates': {
      id: '/_app/admin/export-templates'
      path: '/export-templates'
      fullPath: '/admin/export-templates'
      preLoaderRoute: typeof AppAdminExportTemplatesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/metrics': {
      id: '/_app/admin/metrics'
      path: '/metrics'
      fullPath: '/admin/metrics'
      preLoaderRoute: typeof AppAdminMetricsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/permissions': {
      id: '/_app/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AppAdminPermissionsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/role-limits': {
      id: '/_app/admin/role-limits'
      path: '/role-limits'
      fullPath: '/admin/role-limits'
      preLoaderRoute: typeof AppAdminRoleLimitsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/roles': {
      id: '/_app/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AppAdminRolesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/sod-rules': {
      id: '/_app/admin/sod-rules'
      path: '/sod-rules'
      fullPath: '/admin/sod-rules'
      preLoaderRoute: typeof AppAdminSodRulesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/tenants': {
      id: '/_app/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AppAdminTenantsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/user-management': {
      id: '/_app/admin/user-management'
      path: '/user-management'
      fullPath: '/admin/user-management'
      preLoaderRoute: typeof AppAdminUserManagementRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/credit-notes/': {
      id: '/_app/credit-notes/'
      path: '/credit-notes'
      fullPath: '/credit-notes/'
      preLoaderRoute: typeof AppCreditNotesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credit-notes/$id': {
      id: '/_app/credit-notes/$id'
      path: '/credit-notes/$id'
      fullPath: '/credit-notes/$id'
      preLoaderRoute: typeof AppCreditNotesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$id': {
      id: '/_app/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/delivery-notes/': {
      id: '/_app/delivery-notes/'
      path: '/delivery-notes'
      fullPath: '/delivery-notes/'
      preLoaderRoute: typeof AppDeliveryNotesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/delivery-notes/$id': {
      id: '/_app/delivery-notes/$id'
      path: '/delivery-notes/$id'
      fullPath: '/delivery-notes/$id'
      preLoaderRoute: typeof AppDeliveryNotesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/': {
      id: '/_app/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof AppEmployeesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/$id': {
      id: '/_app/employees/$id'
      path: '/employees/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof AppEmployeesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goods-receipts/': {
      id: '/_app/goods-receipts/'
      path: '/goods-receipts'
      fullPath: '/goods-receipts/'
      preLoaderRoute: typeof AppGoodsReceiptsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goods-receipts/$id': {
      id: '/_app/goods-receipts/$id'
      path: '/goods-receipts/$id'
      fullPath: '/goods-receipts/$id'
      preLoaderRoute: typeof AppGoodsReceiptsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$id': {
      id: '/_app/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AppInvoicesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/$id': {
      id: '/_app/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AppProductsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase-invoices/': {
      id: '/_app/purchase-invoices/'
      path: '/purchase-invoices'
      fullPath: '/purchase-invoices/'
      preLoaderRoute: typeof AppPurchaseInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase-invoices/$id': {
      id: '/_app/purchase-invoices/$id'
      path: '/purchase-invoices/$id'
      fullPath: '/purchase-invoices/$id'
      preLoaderRoute: typeof AppPurchaseInvoicesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase-invoices/approvals': {
      id: '/_app/purchase-invoices/approvals'
      path: '/purchase-invoices/approvals'
      fullPath: '/purchase-invoices/approvals'
      preLoaderRoute: typeof AppPurchaseInvoicesApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase-orders/': {
      id: '/_app/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof AppPurchaseOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase-orders/$id': {
      id: '/_app/purchase-orders/$id'
      path: '/purchase-orders/$id'
      fullPath: '/purchase-orders/$id'
      preLoaderRoute: typeof AppPurchaseOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotations/': {
      id: '/_app/quotations/'
      path: '/quotations'
      fullPath: '/quotations/'
      preLoaderRoute: typeof AppQuotationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotations/$id': {
      id: '/_app/quotations/$id'
      path: '/quotations/$id'
      fullPath: '/quotations/$id'
      preLoaderRoute: typeof AppQuotationsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/': {
      id: '/_app/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AppQuotesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/new': {
      id: '/_app/quotes/new'
      path: '/quotes/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof AppQuotesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/returns': {
      id: '/_app/reports/returns'
      path: '/reports/returns'
      fullPath: '/reports/returns'
      preLoaderRoute: typeof AppReportsReturnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/sales': {
      id: '/_app/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof AppReportsSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales-orders/': {
      id: '/_app/sales-orders/'
      path: '/sales-orders'
      fullPath: '/sales-orders/'
      preLoaderRoute: typeof AppSalesOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales-orders/$id': {
      id: '/_app/sales-orders/$id'
      path: '/sales-orders/$id'
      fullPath: '/sales-orders/$id'
      preLoaderRoute: typeof AppSalesOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/alerts': {
      id: '/_app/settings/alerts'
      path: '/settings/alerts'
      fullPath: '/settings/alerts'
      preLoaderRoute: typeof AppSettingsAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers/': {
      id: '/_app/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AppSuppliersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers/$id': {
      id: '/_app/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof AppSuppliersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/treasury/': {
      id: '/_app/treasury/'
      path: '/treasury'
      fullPath: '/treasury/'
      preLoaderRoute: typeof AppTreasuryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/treasury/$id': {
      id: '/_app/treasury/$id'
      path: '/treasury/$id'
      fullPath: '/treasury/$id'
      preLoaderRoute: typeof AppTreasuryIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/platform/tenants/': {
      id: '/platform/tenants/'
      path: '/tenants'
      fullPath: '/platform/tenants/'
      preLoaderRoute: typeof PlatformTenantsIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/tenants/$id': {
      id: '/platform/tenants/$id'
      path: '/tenants/$id'
      fullPath: '/platform/tenants/$id'
      preLoaderRoute: typeof PlatformTenantsIdRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_app/admin/dispatcher-batches/': {
      id: '/_app/admin/dispatcher-batches/'
      path: '/dispatcher-batches'
      fullPath: '/admin/dispatcher-batches/'
      preLoaderRoute: typeof AppAdminDispatcherBatchesIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/dispatcher-batches/$correlationId': {
      id: '/_app/admin/dispatcher-batches/$correlationId'
      path: '/dispatcher-batches/$correlationId'
      fullPath: '/admin/dispatcher-batches/$correlationId'
      preLoaderRoute: typeof AppAdminDispatcherBatchesCorrelationIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminActivityLogRoute: typeof AppAdminActivityLogRoute
  AppAdminApprovalChainsRoute: typeof AppAdminApprovalChainsRoute
  AppAdminAuditTrailRoute: typeof AppAdminAuditTrailRoute
  AppAdminBackupRoute: typeof AppAdminBackupRoute
  AppAdminCustomizationsRoute: typeof AppAdminCustomizationsRoute
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAdminDomainEventsRoute: typeof AppAdminDomainEventsRoute
  AppAdminExportTemplatesRoute: typeof AppAdminExportTemplatesRoute
  AppAdminMetricsRoute: typeof AppAdminMetricsRoute
  AppAdminPermissionsRoute: typeof AppAdminPermissionsRoute
  AppAdminRoleLimitsRoute: typeof AppAdminRoleLimitsRoute
  AppAdminRolesRoute: typeof AppAdminRolesRoute
  AppAdminSodRulesRoute: typeof AppAdminSodRulesRoute
  AppAdminTenantsRoute: typeof AppAdminTenantsRoute
  AppAdminUserManagementRoute: typeof AppAdminUserManagementRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminDispatcherBatchesCorrelationIdRoute: typeof AppAdminDispatcherBatchesCorrelationIdRoute
  AppAdminDispatcherBatchesIndexRoute: typeof AppAdminDispatcherBatchesIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminActivityLogRoute: AppAdminActivityLogRoute,
  AppAdminApprovalChainsRoute: AppAdminApprovalChainsRoute,
  AppAdminAuditTrailRoute: AppAdminAuditTrailRoute,
  AppAdminBackupRoute: AppAdminBackupRoute,
  AppAdminCustomizationsRoute: AppAdminCustomizationsRoute,
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAdminDomainEventsRoute: AppAdminDomainEventsRoute,
  AppAdminExportTemplatesRoute: AppAdminExportTemplatesRoute,
  AppAdminMetricsRoute: AppAdminMetricsRoute,
  AppAdminPermissionsRoute: AppAdminPermissionsRoute,
  AppAdminRoleLimitsRoute: AppAdminRoleLimitsRoute,
  AppAdminRolesRoute: AppAdminRolesRoute,
  AppAdminSodRulesRoute: AppAdminSodRulesRoute,
  AppAdminTenantsRoute: AppAdminTenantsRoute,
  AppAdminUserManagementRoute: AppAdminUserManagementRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminDispatcherBatchesCorrelationIdRoute:
    AppAdminDispatcherBatchesCorrelationIdRoute,
  AppAdminDispatcherBatchesIndexRoute: AppAdminDispatcherBatchesIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAttachmentsRoute: typeof AppAttachmentsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppCollectionsRoute: typeof AppCollectionsRoute
  AppExpenseCategoriesRoute: typeof AppExpenseCategoriesRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppInstallRoute: typeof AppInstallRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppKpisRoute: typeof AppKpisRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOpenFileRoute: typeof AppOpenFileRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPriceListsRoute: typeof AppPriceListsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProtocolRoute: typeof AppProtocolRoute
  AppSalesPipelineRoute: typeof AppSalesPipelineRoute
  AppSearchRoute: typeof AppSearchRoute
  AppShareTargetRoute: typeof AppShareTargetRoute
  AppSupplierPaymentsRoute: typeof AppSupplierPaymentsRoute
  AppSyncRoute: typeof AppSyncRoute
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAccountingChartOfAccountsRoute: typeof AppAccountingChartOfAccountsRoute
  AppAccountingJournalsRoute: typeof AppAccountingJournalsRoute
  AppAccountingPostingLogRoute: typeof AppAccountingPostingLogRoute
  AppCreditNotesIdRoute: typeof AppCreditNotesIdRoute
  AppCustomersIdRoute: typeof AppCustomersIdRoute
  AppDeliveryNotesIdRoute: typeof AppDeliveryNotesIdRoute
  AppEmployeesIdRoute: typeof AppEmployeesIdRoute
  AppGoodsReceiptsIdRoute: typeof AppGoodsReceiptsIdRoute
  AppInvoicesIdRoute: typeof AppInvoicesIdRoute
  AppProductsIdRoute: typeof AppProductsIdRoute
  AppPurchaseInvoicesIdRoute: typeof AppPurchaseInvoicesIdRoute
  AppPurchaseInvoicesApprovalsRoute: typeof AppPurchaseInvoicesApprovalsRoute
  AppPurchaseOrdersIdRoute: typeof AppPurchaseOrdersIdRoute
  AppQuotationsIdRoute: typeof AppQuotationsIdRoute
  AppQuotesNewRoute: typeof AppQuotesNewRoute
  AppReportsReturnsRoute: typeof AppReportsReturnsRoute
  AppReportsSalesRoute: typeof AppReportsSalesRoute
  AppSalesOrdersIdRoute: typeof AppSalesOrdersIdRoute
  AppSettingsAlertsRoute: typeof AppSettingsAlertsRoute
  AppSuppliersIdRoute: typeof AppSuppliersIdRoute
  AppTreasuryIdRoute: typeof AppTreasuryIdRoute
  AppAccountingIndexRoute: typeof AppAccountingIndexRoute
  AppCreditNotesIndexRoute: typeof AppCreditNotesIndexRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppDeliveryNotesIndexRoute: typeof AppDeliveryNotesIndexRoute
  AppEmployeesIndexRoute: typeof AppEmployeesIndexRoute
  AppGoodsReceiptsIndexRoute: typeof AppGoodsReceiptsIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppPurchaseInvoicesIndexRoute: typeof AppPurchaseInvoicesIndexRoute
  AppPurchaseOrdersIndexRoute: typeof AppPurchaseOrdersIndexRoute
  AppQuotationsIndexRoute: typeof AppQuotationsIndexRoute
  AppQuotesIndexRoute: typeof AppQuotesIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppSalesOrdersIndexRoute: typeof AppSalesOrdersIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSuppliersIndexRoute: typeof AppSuppliersIndexRoute
  AppTreasuryIndexRoute: typeof AppTreasuryIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppApprovalsRoute: AppApprovalsRoute,
  AppAttachmentsRoute: AppAttachmentsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppCollectionsRoute: AppCollectionsRoute,
  AppExpenseCategoriesRoute: AppExpenseCategoriesRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppInstallRoute: AppInstallRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppKpisRoute: AppKpisRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOpenFileRoute: AppOpenFileRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPriceListsRoute: AppPriceListsRoute,
  AppProfileRoute: AppProfileRoute,
  AppProtocolRoute: AppProtocolRoute,
  AppSalesPipelineRoute: AppSalesPipelineRoute,
  AppSearchRoute: AppSearchRoute,
  AppShareTargetRoute: AppShareTargetRoute,
  AppSupplierPaymentsRoute: AppSupplierPaymentsRoute,
  AppSyncRoute: AppSyncRoute,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
  AppAccountingChartOfAccountsRoute: AppAccountingChartOfAccountsRoute,
  AppAccountingJournalsRoute: AppAccountingJournalsRoute,
  AppAccountingPostingLogRoute: AppAccountingPostingLogRoute,
  AppCreditNotesIdRoute: AppCreditNotesIdRoute,
  AppCustomersIdRoute: AppCustomersIdRoute,
  AppDeliveryNotesIdRoute: AppDeliveryNotesIdRoute,
  AppEmployeesIdRoute: AppEmployeesIdRoute,
  AppGoodsReceiptsIdRoute: AppGoodsReceiptsIdRoute,
  AppInvoicesIdRoute: AppInvoicesIdRoute,
  AppProductsIdRoute: AppProductsIdRoute,
  AppPurchaseInvoicesIdRoute: AppPurchaseInvoicesIdRoute,
  AppPurchaseInvoicesApprovalsRoute: AppPurchaseInvoicesApprovalsRoute,
  AppPurchaseOrdersIdRoute: AppPurchaseOrdersIdRoute,
  AppQuotationsIdRoute: AppQuotationsIdRoute,
  AppQuotesNewRoute: AppQuotesNewRoute,
  AppReportsReturnsRoute: AppReportsReturnsRoute,
  AppReportsSalesRoute: AppReportsSalesRoute,
  AppSalesOrdersIdRoute: AppSalesOrdersIdRoute,
  AppSettingsAlertsRoute: AppSettingsAlertsRoute,
  AppSuppliersIdRoute: AppSuppliersIdRoute,
  AppTreasuryIdRoute: AppTreasuryIdRoute,
  AppAccountingIndexRoute: AppAccountingIndexRoute,
  AppCreditNotesIndexRoute: AppCreditNotesIndexRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppDeliveryNotesIndexRoute: AppDeliveryNotesIndexRoute,
  AppEmployeesIndexRoute: AppEmployeesIndexRoute,
  AppGoodsReceiptsIndexRoute: AppGoodsReceiptsIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppPurchaseInvoicesIndexRoute: AppPurchaseInvoicesIndexRoute,
  AppPurchaseOrdersIndexRoute: AppPurchaseOrdersIndexRoute,
  AppQuotationsIndexRoute: AppQuotationsIndexRoute,
  AppQuotesIndexRoute: AppQuotesIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppSalesOrdersIndexRoute: AppSalesOrdersIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSuppliersIndexRoute: AppSuppliersIndexRoute,
  AppTreasuryIndexRoute: AppTreasuryIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PlatformRouteChildren {
  PlatformAdminsRoute: typeof PlatformAdminsRoute
  PlatformBillingRoute: typeof PlatformBillingRoute
  PlatformReportsRoute: typeof PlatformReportsRoute
  PlatformSettingsRoute: typeof PlatformSettingsRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  PlatformTenantsIdRoute: typeof PlatformTenantsIdRoute
  PlatformTenantsIndexRoute: typeof PlatformTenantsIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformAdminsRoute: PlatformAdminsRoute,
  PlatformBillingRoute: PlatformBillingRoute,
  PlatformReportsRoute: PlatformReportsRoute,
  PlatformSettingsRoute: PlatformSettingsRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  PlatformTenantsIdRoute: PlatformTenantsIdRoute,
  PlatformTenantsIndexRoute: PlatformTenantsIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  Char91indexChar93Route: Char91indexChar93Route,
  LandingRoute: LandingRoute,
  PlatformRoute: PlatformRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91__integration__Char93Ux1eRoute: Char91__integration__Char93Ux1eRoute,
  DevPdfJobsRoute: DevPdfJobsRoute,
  DevPdfSandboxRoute: DevPdfSandboxRoute,
  DevPdfTelemetryRoute: DevPdfTelemetryRoute,
  PlatformAuthRoute: PlatformAuthRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
